### ISSUE TITLE
TeStS aRe InCoMpLeTe PlZ fIx

### ISSUE THREAD

**Issue by Torsitano** [mikejgray/spongebobify#1]
cAnNoT pUt InTo PrOdUcTiOn WiTh InAdEqUaTe TeSt CoVeRaGe, pLz FiX

**Comment by mikejgray** [comment]
pRs wELcOMe

**Comment by Torsitano** [comment]
bUt ThEn I'd NeEd To LeArN hOw TeStS wOrK

![fail](https://user-images.githubusercontent.com/58057426/156681278-ad1857b4-0e5a-4325-956a-bf0ab029d26c.JPG)

**Comment by mikejgray** [comment]
#2 resolves
